/**
 * Router Setup
 *
 * Creates the browser router from the route configuration.
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import { createBrowserRouter } from 'react-router-dom'
import { routes } from './routes'

export { Path, buildPath } from './paths'
export const router = createBrowserRouter(routes)
