/**
 * Application Route Paths
 *
 * Central registry of all route paths used in the application.
 * Use these enums instead of hardcoded strings for type-safe navigation.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

export enum Path {
  Home = '/',
  Login = '/login',
  Register = '/register',
  ForgotPassword = '/forgot-password',
  ResetPassword = '/reset-password/:token',
  Dashboard = '/dashboard',
  // blacksmith:path
}

/**
 * Build a path with dynamic parameters replaced.
 *
 * @example
 *   buildPath(Path.ResetPassword, { token: 'abc123' })
 *   // => '/reset-password/abc123'
 */
export function buildPath(
  path: Path,
  params?: Record<string, string>,
): string {
  let result: string = path
  if (params) {
    for (const [key, value] of Object.entries(params)) {
      result = result.replace(`:${key}`, encodeURIComponent(value))
    }
  }
  return result
}
