/**
 * Application Routes
 *
 * Assembles route objects exported from each page/feature.
 * Each page owns its own routes — this file just composes them.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import { Outlet, type RouteObject } from 'react-router-dom'
import { AuthGuard } from '@/router/auth-guard'
import { MainLayout } from '@/router/layouts/main-layout'
import { AuthLayoutWrapper } from '@/router/layouts/auth-layout'
import { RouteErrorBoundary } from '@/router/error-boundary'
import NotFoundPage from '@/shared/components/not-found-page'
import { homeRoutes } from '@/pages/home'
import { dashboardRoutes } from '@/pages/dashboard'
import { authRoutes } from '@/features/auth'
// blacksmith:import

/**
 * Public routes — accessible without authentication.
 */
const publicRoutes: RouteObject[] = [
  ...homeRoutes,
]

/**
 * Private routes — wrapped in AuthGuard, requires authentication.
 * Add your authenticated routes here.
 */
const privateRoutes: RouteObject[] = [
  ...dashboardRoutes,
  // blacksmith:routes
]

export const routes: RouteObject[] = [
  // Auth pages (login, register, etc.)
  {
    element: <AuthLayoutWrapper />,
    errorElement: <RouteErrorBoundary />,
    children: authRoutes,
  },

  // App pages
  {
    element: <MainLayout />,
    errorElement: <RouteErrorBoundary />,
    children: [
      ...publicRoutes,
      {
        element: (
          <AuthGuard>
            <Outlet />
          </AuthGuard>
        ),
        children: privateRoutes,
      },
    ],
  },

  // Catch-all 404
  { path: '*', element: <NotFoundPage /> },
]
