"""
Shared pytest fixtures for Clinic appointment booking.

Fixtures defined here are available to every test without importing.
Generated by Blacksmith. You own this file — customize as needed.
"""

import pytest
from rest_framework.test import APIClient

TEST_PASSWORD = 'TestPass123!'


@pytest.fixture
def test_password():
    """The password every fixture user is created with."""
    return TEST_PASSWORD


@pytest.fixture
def api_client():
    """An unauthenticated DRF test client."""
    return APIClient()


@pytest.fixture
def user(db, django_user_model):
    """A saved, ordinary user."""
    return django_user_model.objects.create_user(
        email='test@example.com',
        password=TEST_PASSWORD,
        first_name='Test',
    )


@pytest.fixture
def other_user(db, django_user_model):
    """A second user, for testing ownership and permission boundaries."""
    return django_user_model.objects.create_user(
        email='other@example.com',
        password=TEST_PASSWORD,
        first_name='Other',
    )


@pytest.fixture
def admin_user(db, django_user_model):
    """A superuser."""
    return django_user_model.objects.create_superuser(
        email='admin@example.com',
        password=TEST_PASSWORD,
        first_name='Admin',
    )


@pytest.fixture
def auth_client(api_client, user):
    """A DRF test client authenticated as `user`."""
    api_client.force_authenticate(user=user)
    return api_client
