/**
 * Forgot Password Page
 *
 * Password reset request form built with Chakra UI.
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import { useState } from 'react'
import {
  Box,
  Button,
  FormControl,
  FormLabel,
  Input,
  VStack,
  Heading,
  Text,
  Alert,
  AlertIcon,
  AlertDescription,
  Link as ChakraLink,
} from '@chakra-ui/react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../hooks/use-auth'
import { Path } from '@/router/paths'

export default function ForgotPasswordPage() {
  const navigate = useNavigate()
  const { sendPasswordResetEmail, error } = useAuth()

  const [email, setEmail] = useState('')
  const [loading, setLoading] = useState(false)
  const [sent, setSent] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true)
    try {
      await sendPasswordResetEmail(email)
      setSent(true)
    } finally {
      setLoading(false)
    }
  }

  return (
    <Box>
      <VStack spacing={2} mb={6} align="start">
        <Heading size="lg">Forgot Password</Heading>
        <Text color="gray.500">
          Enter your email and we'll send you a reset link.
        </Text>
      </VStack>

      {error && (
        <Alert status="error" borderRadius="md" mb={4}>
          <AlertIcon />
          <AlertDescription>{error.message}</AlertDescription>
        </Alert>
      )}

      {sent && (
        <Alert status="success" borderRadius="md" mb={4}>
          <AlertIcon />
          <AlertDescription>
            If an account with that email exists, a reset link has been sent.
          </AlertDescription>
        </Alert>
      )}

      <form onSubmit={handleSubmit}>
        <VStack spacing={4}>
          <FormControl isRequired>
            <FormLabel>Email</FormLabel>
            <Input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="you@example.com"
            />
          </FormControl>

          <Button
            type="submit"
            colorScheme="blue"
            width="full"
            isLoading={loading}
          >
            Send Reset Link
          </Button>
        </VStack>
      </form>

      <Text fontSize="sm" color="gray.500" mt={6} textAlign="center">
        <ChakraLink color="blue.500" onClick={() => navigate(Path.Login)}>
          Back to Sign In
        </ChakraLink>
      </Text>
    </Box>
  )
}
