/**
 * Login Page
 *
 * Login form built with Chakra UI, connected to Django JWT backend.
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import { useState } from 'react'
import {
  Box,
  Button,
  FormControl,
  FormLabel,
  Input,
  VStack,
  Heading,
  Text,
  Alert,
  AlertIcon,
  AlertDescription,
  Link as ChakraLink,
} from '@chakra-ui/react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { useAuth } from '../hooks/use-auth'
import { Path } from '@/router/paths'

export default function LoginPage() {
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()
  const { login, error, isLoading } = useAuth()

  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')

  const redirectTo = searchParams.get('redirect') || Path.Home

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    const result = await login(email, password)
    if (result.success) {
      navigate(redirectTo, { replace: true })
    }
  }

  return (
    <Box>
      <VStack spacing={2} mb={6} align="start">
        <Heading size="lg">Sign In</Heading>
        <Text color="gray.500">Enter your credentials to access your account.</Text>
      </VStack>

      {error && (
        <Alert status="error" borderRadius="md" mb={4}>
          <AlertIcon />
          <AlertDescription>{error.message}</AlertDescription>
        </Alert>
      )}

      <form onSubmit={handleSubmit}>
        <VStack spacing={4}>
          <FormControl isRequired>
            <FormLabel>Email</FormLabel>
            <Input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="you@example.com"
            />
          </FormControl>

          <FormControl isRequired>
            <FormLabel>Password</FormLabel>
            <Input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="Enter your password"
            />
          </FormControl>

          <Button
            type="submit"
            colorScheme="blue"
            width="full"
            isLoading={isLoading}
          >
            Sign In
          </Button>
        </VStack>
      </form>

      <VStack spacing={2} mt={6}>
        <ChakraLink
          color="blue.500"
          fontSize="sm"
          onClick={() => navigate(Path.ForgotPassword)}
        >
          Forgot your password?
        </ChakraLink>
        <Text fontSize="sm" color="gray.500">
          Don't have an account?{' '}
          <ChakraLink color="blue.500" onClick={() => navigate(Path.Register)}>
            Sign Up
          </ChakraLink>
        </Text>
      </VStack>
    </Box>
  )
}
