/**
 * Register Page
 *
 * Registration form built with Chakra UI, connected to Django JWT backend.
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import { useState } from 'react'
import {
  Box,
  Button,
  FormControl,
  FormLabel,
  Input,
  VStack,
  Heading,
  Text,
  Alert,
  AlertIcon,
  AlertDescription,
  Link as ChakraLink,
} from '@chakra-ui/react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../hooks/use-auth'
import { Path } from '@/router/paths'

export default function RegisterPage() {
  const navigate = useNavigate()
  const { register, error, isLoading } = useAuth()

  const [displayName, setDisplayName] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    const result = await register(email, password, displayName)
    if (result.success) {
      navigate(Path.Home, { replace: true })
    }
  }

  return (
    <Box>
      <VStack spacing={2} mb={6} align="start">
        <Heading size="lg">Create Account</Heading>
        <Text color="gray.500">Sign up to get started.</Text>
      </VStack>

      {error && (
        <Alert status="error" borderRadius="md" mb={4}>
          <AlertIcon />
          <AlertDescription>{error.message}</AlertDescription>
        </Alert>
      )}

      <form onSubmit={handleSubmit}>
        <VStack spacing={4}>
          <FormControl>
            <FormLabel>Name</FormLabel>
            <Input
              value={displayName}
              onChange={(e) => setDisplayName(e.target.value)}
              placeholder="Your name"
            />
          </FormControl>

          <FormControl isRequired>
            <FormLabel>Email</FormLabel>
            <Input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="you@example.com"
            />
          </FormControl>

          <FormControl isRequired>
            <FormLabel>Password</FormLabel>
            <Input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="Choose a password"
            />
          </FormControl>

          <Button
            type="submit"
            colorScheme="blue"
            width="full"
            isLoading={isLoading}
          >
            Create Account
          </Button>
        </VStack>
      </form>

      <Text fontSize="sm" color="gray.500" mt={6} textAlign="center">
        Already have an account?{' '}
        <ChakraLink color="blue.500" onClick={() => navigate(Path.Login)}>
          Sign In
        </ChakraLink>
      </Text>
    </Box>
  )
}
