/**
 * Reset Password Page
 *
 * Password reset form built with Chakra UI.
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import { useState } from 'react'
import {
  Box,
  Button,
  FormControl,
  FormLabel,
  Input,
  VStack,
  Heading,
  Text,
  Alert,
  AlertIcon,
  AlertDescription,
  Link as ChakraLink,
} from '@chakra-ui/react'
import { useNavigate, useParams } from 'react-router-dom'
import { useAuth } from '../hooks/use-auth'
import { Path } from '@/router/paths'

export default function ResetPasswordPage() {
  const navigate = useNavigate()
  const { token } = useParams<{ token: string }>()
  const { confirmPasswordReset, error } = useAuth()

  const [password, setPassword] = useState('')
  const [loading, setLoading] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true)
    try {
      const result = await confirmPasswordReset(token || '', password)
      if (result.success) {
        navigate(Path.Login, { replace: true })
      }
    } finally {
      setLoading(false)
    }
  }

  return (
    <Box>
      <VStack spacing={2} mb={6} align="start">
        <Heading size="lg">Reset Password</Heading>
        <Text color="gray.500">Enter your new password below.</Text>
      </VStack>

      {error && (
        <Alert status="error" borderRadius="md" mb={4}>
          <AlertIcon />
          <AlertDescription>{error.message}</AlertDescription>
        </Alert>
      )}

      <form onSubmit={handleSubmit}>
        <VStack spacing={4}>
          <FormControl isRequired>
            <FormLabel>New Password</FormLabel>
            <Input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="Choose a new password"
            />
          </FormControl>

          <Button
            type="submit"
            colorScheme="blue"
            width="full"
            isLoading={loading}
          >
            Reset Password
          </Button>
        </VStack>
      </form>

      <Text fontSize="sm" color="gray.500" mt={6} textAlign="center">
        <ChakraLink color="blue.500" onClick={() => navigate(Path.Login)}>
          Back to Sign In
        </ChakraLink>
      </Text>
    </Box>
  )
}
