"""
Tests for the users app.

Fixtures (api_client, user, auth_client, ...) come from the project-level
conftest.py and need no import.

Generated by Blacksmith. You own this file — customize as needed.
"""

import pytest
from rest_framework import status

REGISTER_URL = '/api/auth/register/'
LOGIN_URL = '/api/auth/login/'
ME_URL = '/api/auth/me/'
CHANGE_PASSWORD_URL = '/api/auth/change-password/'


@pytest.fixture
def registration_payload(test_password):
    return {
        'email': 'new@example.com',
        'first_name': 'New',
        'password': test_password,
        'password_confirm': test_password,
    }


class TestRegister:
    def test_returns_tokens(self, api_client, registration_payload, db):
        response = api_client.post(REGISTER_URL, registration_payload)

        assert response.status_code == status.HTTP_201_CREATED
        assert 'access' in response.data
        assert 'refresh' in response.data

    def test_creates_the_user(self, api_client, registration_payload, django_user_model, db):
        api_client.post(REGISTER_URL, registration_payload)

        assert django_user_model.objects.filter(email='new@example.com').exists()

    def test_rejects_mismatched_passwords(self, api_client, registration_payload, db):
        registration_payload['password_confirm'] = 'SomethingElse123!'

        response = api_client.post(REGISTER_URL, registration_payload)

        assert response.status_code == status.HTTP_400_BAD_REQUEST
        assert 'password_confirm' in response.data

    def test_rejects_duplicate_email(self, api_client, registration_payload, user, db):
        registration_payload['email'] = user.email

        response = api_client.post(REGISTER_URL, registration_payload)

        assert response.status_code == status.HTTP_400_BAD_REQUEST
        assert 'email' in response.data


class TestLogin:
    def test_returns_tokens_for_valid_credentials(self, api_client, user, test_password):
        response = api_client.post(
            LOGIN_URL, {'email': user.email, 'password': test_password}
        )

        assert response.status_code == status.HTTP_200_OK
        assert 'access' in response.data
        assert 'refresh' in response.data

    def test_rejects_a_wrong_password(self, api_client, user):
        response = api_client.post(
            LOGIN_URL, {'email': user.email, 'password': 'WrongPassword123!'}
        )

        assert response.status_code == status.HTTP_400_BAD_REQUEST

    def test_rejects_an_unknown_email(self, api_client, db, test_password):
        response = api_client.post(
            LOGIN_URL, {'email': 'nobody@example.com', 'password': test_password}
        )

        assert response.status_code == status.HTTP_400_BAD_REQUEST


class TestMe:
    def test_returns_the_current_user(self, auth_client, user):
        response = auth_client.get(ME_URL)

        assert response.status_code == status.HTTP_200_OK
        assert response.data['email'] == user.email

    def test_requires_authentication(self, api_client, db):
        response = api_client.get(ME_URL)

        assert response.status_code == status.HTTP_401_UNAUTHORIZED

    def test_updates_the_profile(self, auth_client, user):
        response = auth_client.patch(ME_URL, {'first_name': 'Renamed'})

        assert response.status_code == status.HTTP_200_OK
        assert response.data['first_name'] == 'Renamed'
        user.refresh_from_db()
        assert user.first_name == 'Renamed'

    def test_does_not_allow_changing_email(self, auth_client, user):
        original = user.email

        auth_client.patch(ME_URL, {'email': 'hacked@example.com'})

        user.refresh_from_db()
        assert user.email == original


class TestChangePassword:
    def test_changes_the_password(self, auth_client, user, test_password):
        response = auth_client.post(
            CHANGE_PASSWORD_URL,
            {'old_password': test_password, 'new_password': 'BrandNewPass456!'},
        )

        assert response.status_code == status.HTTP_200_OK
        user.refresh_from_db()
        assert user.check_password('BrandNewPass456!')

    def test_rejects_a_wrong_old_password(self, auth_client, user, test_password):
        response = auth_client.post(
            CHANGE_PASSWORD_URL,
            {'old_password': 'NotMyPassword1!', 'new_password': 'BrandNewPass456!'},
        )

        assert response.status_code == status.HTTP_400_BAD_REQUEST
        user.refresh_from_db()
        assert user.check_password(test_password)

    def test_requires_authentication(self, api_client, db, test_password):
        response = api_client.post(
            CHANGE_PASSWORD_URL,
            {'old_password': test_password, 'new_password': 'BrandNewPass456!'},
        )

        assert response.status_code == status.HTTP_401_UNAUTHORIZED


class TestUserModel:
    def test_str_is_the_email(self, user):
        assert str(user) == user.email

    def test_create_user_requires_an_email(self, django_user_model, db, test_password):
        with pytest.raises(ValueError):
            django_user_model.objects.create_user(email='', password=test_password)

    def test_create_superuser_sets_the_flags(self, admin_user):
        assert admin_user.is_staff
        assert admin_user.is_superuser
