/**
 * Auth Adapter
 *
 * Connects the auth system to the Django JWT backend.
 * Implements the AuthAdapter interface using the generated API client.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import type { AuthAdapter, AuthUser, AuthError, SocialProvider } from './types'
import { setTokens, getAccessToken, clearTokens } from '@/api/client'
import { parseApiError } from '@/shared/hooks/api-error'

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000'

// Internal state
let currentUser: AuthUser | null = null
let authListeners: Array<(user: AuthUser | null) => void> = []

function notifyListeners(user: AuthUser | null) {
  currentUser = user
  authListeners.forEach((cb) => cb(user))
}

function mapDjangoUser(data: any): AuthUser {
  return {
    id: String(data.id),
    email: data.email,
    displayName: data.first_name
      ? `${data.first_name}${data.last_name ? ' ' + data.last_name : ''}`
      : null,
    photoURL: null,
    emailVerified: true,
    providerId: 'password',
  }
}

function toAuthError(error: unknown): AuthError {
  const parsed = parseApiError(error)

  // If there are field-level errors, include them in the message
  const fieldMessages = Object.entries(parsed.fieldErrors)
    .map(([field, msgs]) => `${field}: ${msgs.join(', ')}`)
    .join('. ')

  const message = fieldMessages
    ? `${parsed.message} ${fieldMessages}`
    : parsed.message

  return { code: `auth/${parsed.status || 'error'}`, message }
}

async function apiFetch(path: string, options: RequestInit = {}): Promise<any> {
  const response = await fetch(`${API_URL}${path}`, {
    headers: {
      'Content-Type': 'application/json',
      ...(getAccessToken() ? { Authorization: `Bearer ${getAccessToken()}` } : {}),
    },
    ...options,
  })

  const data = await response.json().catch(() => null)

  if (!response.ok) {
    throw { status: response.status, error: data || { detail: response.statusText } }
  }

  return data
}

async function fetchCurrentUser(): Promise<AuthUser> {
  const data = await apiFetch('/api/auth/me/')
  return mapDjangoUser(data)
}

export function createAuthAdapter(): AuthAdapter {
  // Try to restore session on init
  ;(async () => {
    try {
      if (getAccessToken()) {
        const user = await fetchCurrentUser()
        notifyListeners(user)
      }
    } catch {
      clearTokens()
      notifyListeners(null)
    }
  })()

  return {
    async signInWithEmail(email: string, password: string) {
      try {
        const data = await apiFetch('/api/auth/login/', {
          method: 'POST',
          body: JSON.stringify({ email, password }),
        })

        setTokens(data.access, data.refresh)
        const user = await fetchCurrentUser()
        notifyListeners(user)

        return { success: true, user }
      } catch (error: unknown) {
        return { success: false, error: toAuthError(error) }
      }
    },

    async signUpWithEmail(
      email: string,
      password: string,
      displayName?: string
    ) {
      try {
        const data = await apiFetch('/api/auth/register/', {
          method: 'POST',
          body: JSON.stringify({
            email,
            password,
            password_confirm: password,
            first_name: displayName || '',
          }),
        })

        setTokens(data.access, data.refresh)
        const user = await fetchCurrentUser()
        notifyListeners(user)

        return { success: true, user }
      } catch (error: unknown) {
        return { success: false, error: toAuthError(error) }
      }
    },

    async signInWithSocial(_provider: SocialProvider) {
      return {
        success: false,
        error: {
          code: 'auth/unsupported',
          message: 'Social login is not yet configured. Implement OAuth on the Django backend.',
        },
      }
    },

    async sendPasswordResetEmail(email: string) {
      try {
        await apiFetch('/api/auth/forgot-password/', {
          method: 'POST',
          body: JSON.stringify({ email }),
        })
        return { success: true as const }
      } catch (error: unknown) {
        return { success: false as const, error: toAuthError(error) }
      }
    },

    async confirmPasswordReset(code: string, newPassword: string) {
      try {
        await apiFetch('/api/auth/reset-password/', {
          method: 'POST',
          body: JSON.stringify({
            token: code,
            password: newPassword,
            password_confirm: newPassword,
          }),
        })
        return { success: true as const }
      } catch (error: unknown) {
        return { success: false as const, error: toAuthError(error) }
      }
    },

    async signOut(): Promise<void> {
      try {
        await apiFetch('/api/auth/logout/', {
          method: 'POST',
        })
      } catch {
        // Ignore errors on logout
      }
      clearTokens()
      notifyListeners(null)
    },

    getCurrentUser(): AuthUser | null {
      return currentUser
    },

    onAuthStateChanged(callback: (user: AuthUser | null) => void): () => void {
      authListeners.push(callback)
      // Fire immediately with current state
      callback(currentUser)

      return () => {
        authListeners = authListeners.filter((cb) => cb !== callback)
      }
    },
  }
}
