/**
 * API Client Configuration
 *
 * Configures the @hey-api/client-fetch client with:
 * - Base URL from environment
 * - JWT auth interceptor
 * - CSRF token interceptor (for Django)
 * - 401 token refresh interceptor
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import { createClient } from '@hey-api/client-fetch'

// Create the client directly (no dependency on generated files)
export const client = createClient({
  baseUrl: import.meta.env.VITE_API_URL || 'http://localhost:8000',
})

// In-memory token storage (more secure than localStorage)
let accessToken: string | null = null
let refreshToken: string | null = null

export function setTokens(access: string | null, refresh?: string | null) {
  accessToken = access
  if (refresh !== undefined) {
    refreshToken = refresh
  }
}

export function getAccessToken(): string | null {
  return accessToken
}

export function getRefreshToken(): string | null {
  return refreshToken
}

export function clearTokens() {
  accessToken = null
  refreshToken = null
}

// Auth interceptor — attach JWT to every request
client.interceptors.request.use((request) => {
  if (accessToken) {
    request.headers.set('Authorization', `Bearer ${accessToken}`)
  }
  return request
})

// CSRF interceptor — Django requires this for non-GET requests
client.interceptors.request.use((request) => {
  const csrfToken = document.cookie
    .split('; ')
    .find((row) => row.startsWith('csrftoken='))
    ?.split('=')[1]

  if (csrfToken) {
    request.headers.set('X-CSRFToken', csrfToken)
  }
  return request
})

// 401 interceptor — attempt token refresh, then retry
let isRefreshing = false
let refreshPromise: Promise<boolean> | null = null

async function attemptTokenRefresh(): Promise<boolean> {
  if (!refreshToken) return false

  try {
    const response = await fetch(
      `${import.meta.env.VITE_API_URL || 'http://localhost:8000'}/api/auth/refresh/`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ refresh: refreshToken }),
      }
    )

    if (!response.ok) return false

    const data = await response.json()
    setTokens(data.access, data.refresh)
    return true
  } catch {
    return false
  }
}

client.interceptors.response.use(async (response) => {
  if (response.status === 401 && !response.url.includes('/api/auth/refresh/')) {
    if (!isRefreshing) {
      isRefreshing = true
      refreshPromise = attemptTokenRefresh().finally(() => {
        isRefreshing = false
        refreshPromise = null
      })
    }

    const refreshed = await refreshPromise
    if (!refreshed) {
      clearTokens()
      window.dispatchEvent(new CustomEvent('auth:logout'))
    }
  }
  return response
})

