/**
 * React Query Client Configuration
 *
 * Centralized QueryClient with sensible defaults.
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import { QueryClient } from '@tanstack/react-query'

export const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 5 * 60 * 1000, // 5 minutes before data is considered stale
      gcTime: 30 * 60 * 1000, // 30 minutes in garbage collection cache
      retry: 2, // Retry failed queries twice
      refetchOnWindowFocus: true,
    },
    mutations: {
      retry: 0, // Never retry mutations
    },
  },
})
