/**
 * Auth Hook
 *
 * Provides a convenient interface to the auth context.
 * Import from here so your app has a single auth import path.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import { useAuthContext } from '../components/auth-provider'

export function useAuth() {
  const auth = useAuthContext()

  return {
    user: auth.user,
    isLoading: auth.loading,
    isAuthenticated: !!auth.user,
    error: auth.error,
    login: auth.signInWithEmail,
    register: auth.signUpWithEmail,
    logout: auth.signOut,
    sendPasswordResetEmail: auth.sendPasswordResetEmail,
    confirmPasswordReset: auth.confirmPasswordReset,
  }
}
