/**
 * API Error Parsing
 *
 * Parses Django REST Framework error responses into user-friendly messages.
 * Generated by Blacksmith. You own this file — customize as needed.
 */

export interface ApiError {
  status: number
  message: string
  fieldErrors: Record<string, string[]>
}

const HTTP_ERROR_MESSAGES: Record<number, string> = {
  400: 'The request was invalid. Please check your input.',
  401: 'You need to sign in to continue.',
  403: 'You don\'t have permission to perform this action.',
  404: 'The requested resource was not found.',
  405: 'This action is not allowed.',
  408: 'The request timed out. Please try again.',
  409: 'This conflicts with an existing resource.',
  429: 'Too many requests. Please slow down and try again.',
  500: 'Something went wrong on our end. Please try again later.',
  502: 'The server is temporarily unavailable. Please try again.',
  503: 'The service is currently unavailable. Please try again later.',
}

/**
 * Parse an error thrown by the API client into a structured ApiError.
 *
 * Handles DRF response shapes:
 * - { "detail": "Error message" }
 * - { "non_field_errors": ["Error 1", "Error 2"] }
 * - { "field_name": ["Error 1"], "other_field": ["Error 2"] }
 * - { "field_name": [{ "message": "...", "code": "..." }] }
 * - Plain string responses
 */
export function parseApiError(error: unknown): ApiError {
  const status = getStatusCode(error)
  const body = getErrorBody(error)

  if (!body) {
    return {
      status,
      message: HTTP_ERROR_MESSAGES[status] || 'An unexpected error occurred.',
      fieldErrors: {},
    }
  }

  // String body
  if (typeof body === 'string') {
    return { status, message: body, fieldErrors: {} }
  }

  // Object body — parse DRF error shape
  if (typeof body === 'object' && body !== null) {
    const fieldErrors: Record<string, string[]> = {}
    const generalMessages: string[] = []

    for (const [key, value] of Object.entries(body as Record<string, unknown>)) {
      const messages = normalizeMessages(value)

      if (key === 'detail') {
        generalMessages.push(...messages)
      } else if (key === 'non_field_errors') {
        generalMessages.push(...messages)
      } else {
        fieldErrors[key] = messages
      }
    }

    // If no general message was found, summarize field errors
    const message =
      generalMessages.length > 0
        ? generalMessages.join(' ')
        : Object.keys(fieldErrors).length > 0
          ? 'Please fix the errors below.'
          : HTTP_ERROR_MESSAGES[status] || 'An unexpected error occurred.'

    return { status, message, fieldErrors }
  }

  return {
    status,
    message: HTTP_ERROR_MESSAGES[status] || 'An unexpected error occurred.',
    fieldErrors: {},
  }
}

/**
 * Get a single human-readable error message from any error.
 */
export function getErrorMessage(error: unknown): string {
  return parseApiError(error).message
}

function getStatusCode(error: unknown): number {
  if (error && typeof error === 'object') {
    // @hey-api/client-fetch error shape
    if ('status' in error && typeof (error as any).status === 'number') {
      return (error as any).status
    }
    // Nested response
    if ('response' in error && (error as any).response?.status) {
      return (error as any).response.status
    }
  }
  return 0
}

function getErrorBody(error: unknown): unknown {
  if (error && typeof error === 'object') {
    // @hey-api/client-fetch puts parsed body in `error` or `body`
    if ('error' in error && (error as any).error != null) {
      return (error as any).error
    }
    if ('body' in error && (error as any).body != null) {
      return (error as any).body
    }
    // Some shapes put it in `data`
    if ('data' in error && (error as any).data != null) {
      return (error as any).data
    }
  }
  // Native Error
  if (error instanceof Error) {
    return error.message
  }
  return null
}

function normalizeMessages(value: unknown): string[] {
  if (typeof value === 'string') return [value]
  if (Array.isArray(value)) {
    return value.flatMap((item) => {
      if (typeof item === 'string') return [item]
      if (item && typeof item === 'object' && 'message' in item) {
        return [String(item.message)]
      }
      return [String(item)]
    })
  }
  if (value && typeof value === 'object' && 'message' in value) {
    return [String((value as any).message)]
  }
  return [String(value)]
}
