/**
 * useDebounce Hook
 *
 * Debounces a value by the specified delay.
 * Import from here so your app has a single import path.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import { useState, useEffect } from 'react'

export function useDebounce<T>(value: T, delay: number = 300): T {
  const [debouncedValue, setDebouncedValue] = useState<T>(value)

  useEffect(() => {
    const timer = setTimeout(() => {
      setDebouncedValue(value)
    }, delay)

    return () => {
      clearTimeout(timer)
    }
  }, [value, delay])

  return debouncedValue
}
