/**
 * useApiMutation — Enhanced useMutation for API calls
 *
 * Wraps TanStack useMutation with:
 * - DRF error parsing with field-level and general error messages
 * - Optional query invalidation after success
 *
 * Error state is derived from the mutation's own `error` — no local state.
 *
 * Usage:
 *   const createPost = useApiMutation({
 *     ...blogPostsCreateMutation(),
 *     invalidateKeys: [blogPostsListQueryKey()],
 *   })
 *
 *   // In a form submit handler:
 *   createPost.mutate({ body: { title: 'Hello' } })
 *
 *   // Display the general error message:
 *   {createPost.errorMessage && <Alert variant="destructive">{createPost.errorMessage}</Alert>}
 *
 *   // Access field errors for inline form display:
 *   createPost.fieldErrors.title  // ["This field is required."]
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import {
  useMutation,
  useQueryClient,
  type QueryKey,
  type UseMutationOptions,
  type UseMutationResult,
} from '@tanstack/react-query'
import { parseApiError, type ApiError } from './api-error'
import { useMemo } from 'react'

export interface UseApiMutationOptions<TData, TVariables, TOnMutateResult>
  extends UseMutationOptions<TData, Error, TVariables, TOnMutateResult> {
  /** Query keys to invalidate after a successful mutation */
  invalidateKeys?: QueryKey[]
}

export type UseApiMutationResult<TData, TVariables, TOnMutateResult> =
  UseMutationResult<TData, Error, TVariables, TOnMutateResult> & {
    /** Parsed field-level errors from the last failed mutation (e.g. { email: ["Already exists."] }) */
    fieldErrors: Record<string, string[]>
    /** Parsed API error from the last failed mutation */
    apiError: ApiError | null
    /** Single error message string from the last failed mutation */
    errorMessage: string | null
  }

export function useApiMutation<
  TData = unknown,
  TVariables = void,
  TOnMutateResult = unknown,
>(
  options: UseApiMutationOptions<TData, TVariables, TOnMutateResult>,
): UseApiMutationResult<TData, TVariables, TOnMutateResult> {
  const queryClient = useQueryClient()

  const { invalidateKeys, ...mutationOptions } = options

  const mutation = useMutation<TData, Error, TVariables, TOnMutateResult>({
    ...mutationOptions,
    onSuccess: (...args) => {
      if (invalidateKeys?.length) {
        for (const key of invalidateKeys) {
          queryClient.invalidateQueries({ queryKey: key })
        }
      }
      mutationOptions.onSuccess?.(...args)
    },
  })

  const apiError = useMemo(
    () => (mutation.error ? parseApiError(mutation.error) : null),
    [mutation.error],
  )

  return {
    ...mutation,
    fieldErrors: apiError?.fieldErrors ?? {},
    apiError,
    errorMessage: apiError?.message ?? null,
  }
}
