/**
 * useApiQuery — Enhanced useQuery for API calls
 *
 * Wraps TanStack useQuery with:
 * - Smart retry (skips 401, 403, 404)
 * - Parsed error messages from DRF responses
 * - Typed error state
 *
 * Usage:
 *   const { data, errorMessage } = useApiQuery({
 *     ...blogPostsListOptions({ query: { page: 1 } }),
 *   })
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import {
  useQuery,
  type UseQueryOptions,
  type UseQueryResult,
} from '@tanstack/react-query'
import { parseApiError, type ApiError } from './api-error'

const NON_RETRYABLE_STATUSES = new Set([400, 401, 403, 404, 405, 409, 422])

export type UseApiQueryResult<TData> = UseQueryResult<TData> & {
  errorMessage: string | null
  apiError: ApiError | null
}

export function useApiQuery<
  TQueryFnData = unknown,
  TData = TQueryFnData,
  TQueryKey extends readonly unknown[] = readonly unknown[],
>(
  options: UseQueryOptions<TQueryFnData, Error, TData, TQueryKey>,
): UseApiQueryResult<TData> {
  const result = useQuery<TQueryFnData, Error, TData, TQueryKey>({
    retry: (failureCount, error) => {
      const status = getStatusFromError(error)
      if (NON_RETRYABLE_STATUSES.has(status)) return false
      return failureCount < 2
    },
    ...options,
  })

  const apiError = result.error ? parseApiError(result.error) : null

  return {
    ...result,
    errorMessage: apiError?.message ?? null,
    apiError,
  }
}

function getStatusFromError(error: unknown): number {
  if (error && typeof error === 'object') {
    if ('status' in error && typeof (error as any).status === 'number') {
      return (error as any).status
    }
    if ('response' in error && (error as any).response?.status) {
      return (error as any).response.status
    }
  }
  return 0
}
