/**
 * Root Application Component
 *
 * Composes all providers and the router.
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import { QueryClientProvider } from '@tanstack/react-query'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import { RouterProvider } from 'react-router-dom'
import { ChakraProvider, ColorModeScript } from '@chakra-ui/react'
import theme from '@/theme'
import { queryClient } from '@/api/query-client'
import { AuthProvider } from '@/features/auth/components/auth-provider'
import { router } from '@/router'

// Initialize API client (registers interceptors)
import '@/api/client'

export function App() {
  return (
    <>
      <ColorModeScript initialColorMode={theme.config.initialColorMode} />
      <ChakraProvider theme={theme}>
        <QueryClientProvider client={queryClient}>
          <AuthProvider>
            <RouterProvider router={router} />
          </AuthProvider>
          {import.meta.env.DEV && <ReactQueryDevtools initialIsOpen={false} />}
        </QueryClientProvider>
      </ChakraProvider>
    </>
  )
}
