/**
 * Auth Provider
 *
 * Provides auth state and actions via React context,
 * connected to the Django JWT adapter.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import { createContext, useContext, useState, useEffect, useCallback } from 'react'
import type { ReactNode } from 'react'
import { createAuthAdapter } from '../adapter'
import type { AuthUser, AuthError, AuthResult } from '../types'

interface AuthContextValue {
  user: AuthUser | null
  loading: boolean
  error: AuthError | null
  signInWithEmail: (email: string, password: string) => Promise<AuthResult>
  signUpWithEmail: (email: string, password: string, displayName?: string) => Promise<AuthResult>
  signOut: () => Promise<void>
  sendPasswordResetEmail: (email: string) => Promise<{ success: boolean; error?: AuthError }>
  confirmPasswordReset: (code: string, newPassword: string) => Promise<{ success: boolean; error?: AuthError }>
}

const AuthContext = createContext<AuthContextValue | null>(null)

const adapter = createAuthAdapter()

interface Props {
  children: ReactNode
}

export function AuthProvider({ children }: Props) {
  const [user, setUser] = useState<AuthUser | null>(adapter.getCurrentUser())
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<AuthError | null>(null)

  useEffect(() => {
    const unsubscribe = adapter.onAuthStateChanged((u) => {
      setUser(u)
      setLoading(false)
    })
    return unsubscribe
  }, [])

  const signInWithEmail = useCallback(async (email: string, password: string) => {
    setError(null)
    const result = await adapter.signInWithEmail(email, password)
    if (!result.success && result.error) {
      setError(result.error)
    }
    return result
  }, [])

  const signUpWithEmail = useCallback(async (email: string, password: string, displayName?: string) => {
    setError(null)
    const result = await adapter.signUpWithEmail(email, password, displayName)
    if (!result.success && result.error) {
      setError(result.error)
    }
    return result
  }, [])

  const signOut = useCallback(async () => {
    setError(null)
    await adapter.signOut()
  }, [])

  const sendPasswordResetEmail = useCallback(async (email: string) => {
    setError(null)
    const result = await adapter.sendPasswordResetEmail(email)
    if (!result.success && result.error) {
      setError(result.error)
    }
    return result
  }, [])

  const confirmPasswordReset = useCallback(async (code: string, newPassword: string) => {
    setError(null)
    const result = await adapter.confirmPasswordReset(code, newPassword)
    if (!result.success && result.error) {
      setError(result.error)
    }
    return result
  }, [])

  return (
    <AuthContext.Provider
      value={{
        user,
        loading,
        error,
        signInWithEmail,
        signUpWithEmail,
        signOut,
        sendPasswordResetEmail,
        confirmPasswordReset,
      }}
    >
      {children}
    </AuthContext.Provider>
  )
}

export function useAuthContext() {
  const context = useContext(AuthContext)
  if (!context) {
    throw new Error('useAuthContext must be used within an AuthProvider')
  }
  return context
}
